version: "2.4"
#### Services ####
services:
  #### Secure storage web app ####
  secure-storage-service:
    build: ./src
    image: secure-storage-app
    restart: always
    ports:
      - "5001:5000"
    networks:
      proxy-redirect: null
    mem_limit: 300mb
    volumes:
      - "./publish/:/publish/"
      - "./cfg-data/:/cfg-data/"

#### Networks ####
networks:
  proxy-redirect:
    external: true
