version: "2.4"
services:
  flask:
    build: ./src
    image: secure-storage-app:v1
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - proxy-redirect
    mem_limit: 128mb
    logging:
      options:
        max-size: 10m
        max-file: "2"
      driver: json-file
    volumes:
      - "./publish/:/publish/"
      - "./cfg-data/:/cfg-data/"

networks:
  proxy-redirect:
    external: true