version: "2.4"
services:
  secure-storage-service:
    build: ./src
    image: secure-storage-app
    restart: unless-stopped
    ports:
      - "5001:5000"
    networks:
      proxy-redirect: null
    mem_limit: 300mb
    volumes:
      - "./publish/:/publish/"
      - "./cfg-data/:/cfg-data/"

networks:
  proxy-redirect:
    external: true
